_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 0.0004615170658244136
lr_critic:
    value: 0.000910139549352706
max_length_episode:
    value: 200
noise_clip:
    value: 1.1027315187639353
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.06819612087977223
sigma_explore:
    value: 0.5179140686590212
tau:
    value: 0.3974548618844296
warmup_amount:
    value: 500
