_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 0.00026850393765197653
lr_critic:
    value: 0.0007464977148324162
max_length_episode:
    value: 200
noise_clip:
    value: 1.381303747456017
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.5146945489332111
sigma_explore:
    value: 0.4423276658657773
tau:
    value: 0.0701097343832479
warmup_amount:
    value: 100
