_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 9.16614535058059e-05
lr_critic:
    value: 6.386269472707454e-05
max_length_episode:
    value: 40
noise_clip:
    value: 1.3610300942219085
num_episodes:
    value: 500
policy_interval:
    value: 2
sigma:
    value: 0.22236810554462097
sigma_explore:
    value: 1.872801722986654
tau:
    value: 0.44552257440501514
update_interval:
    value: 1
