_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 5.830238026763127e-05
lr_critic:
    value: 3.54017370762942e-05
max_length_episode:
    value: 200
noise_clip:
    value: 0.11187774441794655
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.802633002493498
sigma_explore:
    value: 0.33760064993712013
tau:
    value: 0.04540890706429144
warmup_amount:
    value: 100
