_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 8.690976020821226e-05
lr_critic:
    value: 4.330458418872109e-06
max_length_episode:
    value: 200
noise_clip:
    value: 1.346102736896818
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.16662911881614997
sigma_explore:
    value: 1.138042802609141
tau:
    value: 0.4969526060360783
update_interval:
    value: 1
