_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.6732623210697651
lr_actor:
    value: 0.005391276112171718
lr_critic:
    value: 0.006620638566376141
max_length_episode:
    value: 200
noise_clip:
    value: 0.6228413424238705
num_episodes:
    value: 50
policy_interval:
    value: 2
sigma:
    value: 0.5936191039346065
sigma_explore:
    value: 0.12089353682460102
tau:
    value: 0.4532632796179712
