_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.882806590177973
lr_actor:
    value: 6.936145578914532e-05
lr_critic:
    value: 0.00794567544545768
max_length_episode:
    value: 200
noise_clip:
    value: 1.7822055488207684
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.30939886344451906
sigma_explore:
    value: 0.08695488952179509
tau:
    value: 0.04119417500604161
update_interval:
    value: 10
