_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 0.0004924126751632224
lr_critic:
    value: 0.0016632843470130562
max_length_episode:
    value: 200
noise_clip:
    value: 1.2070507021498629
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.30848085357663596
sigma_explore:
    value: 0.43147456960130814
tau:
    value: 0.047847425043799734
warmup_amount:
    value: 100
