_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.949416977361622
lr_actor:
    value: 0.00030839509350755857
lr_critic:
    value: 0.005103360276982672
max_length_episode:
    value: 200
noise_clip:
    value: 1.9705983880566
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.03496069420056469
sigma_explore:
    value: 0.10344409507657426
tau:
    value: 0.10505452672716088
update_interval:
    value: 9
