_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.8594835444796084
lr_actor:
    value: 0.0012984747881839343
lr_critic:
    value: 0.003723247065021229
max_length_episode:
    value: 200
noise_clip:
    value: 1.7343088441519203
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.24345145861714568
sigma_explore:
    value: 0.5934068942105359
tau:
    value: 0.03144390536825553
update_interval:
    value: 8
