_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.2592862427485536
lr_actor:
    value: 0.0001786134898525113
lr_critic:
    value: -0.00024356466650613708
max_length_episode:
    value: 200
noise_clip:
    value: 0.8582104002601616
num_episodes:
    value: 50
policy_interval:
    value: 2
sigma:
    value: 0.7677533697612466
tau:
    value: 0.9439331715222028
