_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 512
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 7.03222701662217e-05
lr_critic:
    value: 0.0008074057118963562
max_length_episode:
    value: 40
noise_clip:
    value: 1.7282796066067383
num_episodes:
    value: 500
policy_interval:
    value: 2
sigma:
    value: 0.7247300675982438
sigma_explore:
    value: 0.8844549042380048
tau:
    value: 0.2685700258702269
update_interval:
    value: 1
