_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 1.1666112169793703e-05
lr_critic:
    value: 0.0013734901485722695
max_length_episode:
    value: 200
noise_clip:
    value: 0.8940726410443136
num_episodes:
    value: 100
policy_interval:
    value: 2
sigma:
    value: 0.4908944122877418
sigma_explore:
    value: 0.12307462469346854
tau:
    value: 0.018942663628878267
warmup_amount:
    value: 100
