_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 12
                - 45
                - 54
                - 55
            "2":
                - 12
                - 45
                - 54
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.3
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.3
            "13": windows-amd64
batch_size:
    value: 500
buffer_size:
    value: 50000
gamma:
    value: 0.99
lr_actor:
    value: 0.0002752456057084388
lr_critic:
    value: 0.0006709066679830131
max_length_episode:
    value: 75
noise_clip:
    value: 0.11267808350563574
num_episodes:
    value: 800
policy_interval:
    value: 2
sigma:
    value: 0.8375959762238014
sigma_explore:
    value: 0.7842870837665835
tau:
    value: 0.22856202082210328
warmup_amount:
    value: 1000
